[tool.poetry]
name = "coin-arbitrage"
version = "0.1.0"
description = "The project is about a cryptocurrency arbitrage trading bot that monitors and compares prices across multiple exchanges (Bybit, Binance, Whitebit) to identify arbitrage opportunities."
authors = ["Yura0Bodnar <yuriy575721@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
python-telegram-bot = "^21.10"
python-dotenv = "^1.0.1"
pybit = "^5.9.0"
httpx = "^0.28.1"
aiohttp = "^3.11.11"
pycryptodome = "^3.21.0"
redis = "^5.2.1"
black = "^25.1.0"
flake8 = "^7.1.2"


[tool.poetry.group.dev.dependencies]
bandit = "^1.8.3"
safety = "^3.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
