apiVersion: v1
kind: Secret
metadata:
  name: bybit-api-keys
  namespace: crypto-bot
type: Opaque
data:
  BYBIT_API_KEY: UnQzNEtHSjNWSEE5WGFvUzFPCg==
  BYBIT_API_SECRET: ckkydmI1Q3hhYkI2cVBWb2dJR08xOFpxYkV6UzdVUnFjVE9zCg==