apiVersion: apps/v1
kind: Deployment
metadata:
  name: whitebit-fetcher
  namespace: crypto-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whitebit
  template:
    metadata:
      labels:
        app: whitebit
    spec:
      containers:
      - name: whitebit
        image: yurabodnar/coin_arbitrage-whitebit:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: EXCHANGE_ROLE
          value: "whitebit"