apiVersion: apps/v1
kind: Deployment
metadata:
  name: bybit-fetcher
  namespace: crypto-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bybit
  template:
    metadata:
      labels:
        app: bybit
    spec:
      containers:
      - name: bybit
        image: yurabodnar/coin_arbitrage-bybit:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: EXCHANGE_ROLE
          value: "bybit"